### ISSUE TITLE
ThresholdTransform and fit_constant=False create bad fit [BUG]

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#444]
**Describe the bug**
The fit_constant-parameter in ml.solve() and ThresholdTransform create a bad fit.

**To Reproduce**
In the example directory (pastas\doc\examples), run the following code:
```
import pastas as ps

# load a model with precipitation, evaporation and a well
ml = ps.io.load("data/B28H1808_2.pas")
# add a ThresholdTransform
ml.add_transform(ps.ThresholdTransform())

# solve with fit_constant=True (the default)
ml.solve(noise=False, fit_constant=True)
ml.plots.results()

# solve with fit_constant=False
ml.solve(noise=False, fit_constant=False)
ml.plots.results()
```

**Expected behavior**
I expect the fit to be similar in the case where fit_constant=True (97 %), but it is only 84 % when fit_constant=False,

**Screenshots**

`fit_constant=True`:
![fit_constant=True](https://user-images.githubusercontent.com/18527362/209938388-7c69a92a-67d9-42ed-b8e0-20d01ec8d99f.png)
vs
`fit_constant=False`:
![fit_constant=False](https://user-images.githubusercontent.com/18527362/209938427-9e93d777-06cc-4e5e-8735-da505b5dbfa6.png)

**Python package version**
Python version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]
Numpy version: 1.22.4
Scipy version: 1.9.3
Pandas version: 1.5.2
Pastas version: 0.22.0b
Matplotlib version: 3.6.2

**Additional context**
It seems the order in which the transform is applied and the method in which the constant is calculated from the residuals is wrong. For now I think we should throw an Exception when ThresholdTransform and fit_constant=False are used together.

**Comment by martinvonk** [comment]
fixed with https://github.com/pastas/pastas/commit/62cede50c3466e3805b97bc90bcb47d77f0c68f0 so closing.

**Comment by rubencalje** [comment]
Well, for now we raise and Exception, saying that ThresholdTransform and fit_constant=False cannot be run together. In the future we should make it possible for these options to co-exist, as theoretically it should be possible.

**Comment by mbakker7** [comment]
I agree with @rubencalje. I will reopen this issue as it is now caught but not fixed.

**Comment by raoulcollenteur** [comment]
I suspect this may (partly) also be an optimisation problem, after trying the strategy I posted in discussion #450. Running the following code gives very similar results. I seems however that during the calibration of the second model (when fit_constance is False), the parameter of the ThresholdTransform are insensitive (no change from initial values). 

```
import pastas as ps

# load a model with precipitation, evaporation and a well
ml = ps.io.load("data/B28H1808_2_pastas-0-23-0.pas")
ml.del_stressmodel("Extraction")

# add a ThresholdTransform
ml.add_transform(ps.ThresholdTransform())

# solve with fit_constant=True (the default)
ml.solve(noise=False, fit_constant=True, x_scale="jac", jac="3-point", tr_solver="exact")
ml.plots.results()

# solve with fit_constant=False
ml.solve(noise=False, fit_constant=False, x_scale="jac", jac="3-point", tr_solver="exact", initial=False)
ml.plots.results()
```

**Comment by raoulcollenteur** [comment]
I re-run  this code with pastas 1.5.0b and actually when doing

`ml.solve(noise=False, fit_constant=False)
`
The R2 is 0.94, so very close. I think we can remove the Exception that is currently thrown:

```
msg = "fit_constant needs to be True (for now) when a transform is used"
raise Exception(msg)
```

and close this issue.

**Comment by raoulcollenteur** [comment]
@rubencalje any thoughts on this one?

**Comment by raoulcollenteur** [comment]
Ah now I see! Okay, in that case I think the code as it is makes sense and this issue can be closed as won't fix right?

**Comment by rubencalje** [comment]
I agree
