### ISSUE TITLE
Consistency throughout Pastas when changing frequency

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#65]
It is now easy to to change the frequency, but the way we deal with this change of frequency is not yet consistent. For now, the gain is the gain/ml.settings['freq']. That means that changing the frequency from daily to weekly, the gain will be divided by 7.

This is not yet consistent with the get_block_response function and the plotting methods that depend in it. I think this would be a good issue to solve in the next Pastas release.

**Comment by rubencalje** [comment]
I think this has been solved by Pull Request #109. The upsample and downsample methods are changed, so that the parameters (and thus the gain) do not change when changing frequency.

**Comment by raoulcollenteur** [comment]
Reopening this Issue as the PR was incomplete:
-  the freq arguments in the noise models are still present but unused
- the freq argument are passed through in the residuals and noise methods of the Model class 
- No documentation that the Alpha parameter is now hard-coded as DAY without any possibility to change this.

**Comment by raoulcollenteur** [comment]
Fixed the above, closing again.
